import { User, Project, Task } from "./types";

export const mockUsers: User[] = [
    {
        id: "u1",
        name: "Andi Pratama",
        email: "andi.pratama@company.com",
        avatar: "",
        role: "admin",
        color: "#6366f1",
    },
    {
        id: "u2",
        name: "Budi Santoso",
        email: "budi.santoso@company.com",
        avatar: "",
        role: "member",
        color: "#22c55e",
    },
    {
        id: "u3",
        name: "Citra Dewi",
        email: "citra.dewi@company.com",
        avatar: "",
        role: "member",
        color: "#f59e0b",
    },
    {
        id: "u4",
        name: "Dian Kusuma",
        email: "dian.kusuma@company.com",
        avatar: "",
        role: "member",
        color: "#ec4899",
    },
    {
        id: "u5",
        name: "Eko Saputra",
        email: "eko.saputra@company.com",
        avatar: "",
        role: "viewer",
        color: "#14b8a6",
    },
];

export const currentUser = mockUsers[0];

export const mockProjects: Project[] = [
    {
        id: "p1",
        title: "Website Redesign",
        description: "Pembaruan tampilan website utama perusahaan dengan desain modern dan responsif.",
        color: "#6366f1",
        members: ["u1", "u2", "u3"],
        taskCount: 12,
        completedCount: 4,
        createdAt: "2026-01-15T08:00:00Z",
        updatedAt: "2026-03-05T14:30:00Z",
    },
    {
        id: "p2",
        title: "Mobile App v2.0",
        description: "Pengembangan versi kedua aplikasi mobile dengan fitur offline-first dan notifikasi push.",
        color: "#22c55e",
        members: ["u1", "u3", "u4", "u5"],
        taskCount: 18,
        completedCount: 10,
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-03-06T10:00:00Z",
    },
    {
        id: "p3",
        title: "API Integration",
        description: "Integrasi dengan layanan pihak ketiga: payment gateway, SMS OTP, dan mapping service.",
        color: "#f59e0b",
        members: ["u1", "u2"],
        taskCount: 8,
        completedCount: 8,
        createdAt: "2026-01-20T08:00:00Z",
        updatedAt: "2026-02-28T16:00:00Z",
    },
    {
        id: "p4",
        title: "Data Analytics Dashboard",
        description: "Pembuatan dashboard analytics real-time untuk monitoring KPI bisnis dan penjualan.",
        color: "#ec4899",
        members: ["u2", "u3", "u4"],
        taskCount: 15,
        completedCount: 2,
        createdAt: "2026-02-20T08:00:00Z",
        updatedAt: "2026-03-07T08:00:00Z",
    },
];

export const mockTasks: Task[] = [
    // Project 1 — Website Redesign
    {
        id: "t1",
        projectId: "p1",
        title: "Desain ulang halaman utama (Landing Page)",
        description: "Buat mockup baru di Figma dengan pendekatan hero section yang lebih menarik. Gunakan pallette warna yang sesuai brand guide terbaru.",
        status: "done",
        priority: "high",
        assigneeId: "u3",
        dueDate: "2026-02-20T00:00:00Z",
        startDate: "2026-02-10T00:00:00Z",
        tags: ["design", "frontend"],
        createdAt: "2026-01-15T08:00:00Z",
        updatedAt: "2026-02-20T16:00:00Z",
    },
    {
        id: "t2",
        projectId: "p1",
        title: "Implementasi komponen Header & Navbar baru",
        description: "Koding komponen React berdasarkan desain yang sudah disetujui. Pastikan responsive di semua breakpoint.",
        status: "done",
        priority: "high",
        assigneeId: "u2",
        dueDate: "2026-02-28T00:00:00Z",
        startDate: "2026-02-21T00:00:00Z",
        tags: ["frontend", "react"],
        gitLink: "https://github.com/company/website/pull/42",
        createdAt: "2026-01-15T08:00:00Z",
        updatedAt: "2026-02-28T10:00:00Z",
    },
    {
        id: "t3",
        projectId: "p1",
        title: "Optimisasi performa halaman (Core Web Vitals)",
        description: "Target LCP < 2.5s dan CLS < 0.1. Gunakan lazy loading untuk gambar dan code splitting.",
        status: "in-progress",
        priority: "medium",
        assigneeId: "u2",
        dueDate: "2026-03-15T00:00:00Z",
        startDate: "2026-03-01T00:00:00Z",
        tags: ["performance", "seo"],
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-03-03T14:00:00Z",
    },
    {
        id: "t4",
        projectId: "p1",
        title: "Setup testing E2E dengan Playwright",
        description: "Buat test suite untuk semua user journey utama: login, checkout, dan profile update.",
        status: "todo",
        priority: "medium",
        assigneeId: "u1",
        dueDate: "2026-03-20T00:00:00Z",
        startDate: "2026-03-10T00:00:00Z",
        tags: ["testing", "automation"],
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-02-01T08:00:00Z",
    },
    {
        id: "t5",
        projectId: "p1",
        title: "Integrasi CMS headless (Contentful)",
        description: "Hubungkan website dengan Contentful untuk manajemen konten artikel dan banner.",
        status: "review",
        priority: "high",
        assigneeId: "u3",
        dueDate: "2026-03-10T00:00:00Z",
        startDate: "2026-02-25T00:00:00Z",
        tags: ["cms", "api"],
        gitLink: "https://github.com/company/website/pull/55",
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-03-05T11:00:00Z",
    },
    {
        id: "t6",
        projectId: "p1",
        title: "Deploy ke staging dan UAT testing",
        description: "Deploy build terbaru ke environment staging, koordinasikan UAT bersama tim QA dan stakeholder.",
        status: "todo",
        priority: "low",
        assigneeId: "u1",
        dueDate: "2026-03-25T00:00:00Z",
        startDate: "2026-03-20T00:00:00Z",
        tags: ["deployment", "uat"],
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-02-01T08:00:00Z",
    },

    // Project 2 — Mobile App v2.0
    {
        id: "t7",
        projectId: "p2",
        title: "Arsitektur state management (Zustand)",
        description: "Refactor state management dari Redux ke Zustand untuk mengurangi boilerplate dan meningkatkan performa.",
        status: "done",
        priority: "high",
        assigneeId: "u4",
        dueDate: "2026-02-15T00:00:00Z",
        startDate: "2026-02-01T00:00:00Z",
        tags: ["architecture", "react-native"],
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-02-15T17:00:00Z",
    },
    {
        id: "t8",
        projectId: "p2",
        title: "Fitur offline-first dengan SQLite lokal",
        description: "Implementasi sinkronisasi data offline menggunakan WatermelonDB dan strategi conflict resolution.",
        status: "in-progress",
        priority: "urgent",
        assigneeId: "u1",
        dueDate: "2026-03-12T00:00:00Z",
        startDate: "2026-02-20T00:00:00Z",
        tags: ["offline", "database"],
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
    },
    {
        id: "t9",
        projectId: "p2",
        title: "Push notification dengan Firebase Cloud Messaging",
        description: "Setup FCM untuk Android dan iOS, termasuk background notification handling dan deep-linking.",
        status: "in-progress",
        priority: "high",
        assigneeId: "u3",
        dueDate: "2026-03-10T00:00:00Z",
        startDate: "2026-02-25T00:00:00Z",
        tags: ["notifications", "firebase"],
        createdAt: "2026-02-05T08:00:00Z",
        updatedAt: "2026-03-02T14:00:00Z",
    },
    {
        id: "t10",
        projectId: "p2",
        title: "UI Library Migration ke NativeWind v4",
        description: "Upgrade seluruh styling dari StyleSheet ke NativeWind v4 dan pastikan konsistensi design token.",
        status: "review",
        priority: "medium",
        assigneeId: "u5",
        dueDate: "2026-03-08T00:00:00Z",
        startDate: "2026-02-18T00:00:00Z",
        tags: ["ui", "styling"],
        createdAt: "2026-02-05T08:00:00Z",
        updatedAt: "2026-03-05T16:00:00Z",
    },
    {
        id: "t11",
        projectId: "p2",
        title: "Biometric Authentication (FaceID/Fingerprint)",
        description: "Tambahkan opsi login biometrik menggunakan expo-local-authentication.",
        status: "todo",
        priority: "medium",
        assigneeId: "u4",
        dueDate: "2026-03-18T00:00:00Z",
        startDate: "2026-03-10T00:00:00Z",
        tags: ["security", "auth"],
        createdAt: "2026-02-10T08:00:00Z",
        updatedAt: "2026-02-10T08:00:00Z",
    },

    // Project 4 — Analytics Dashboard
    {
        id: "t12",
        projectId: "p4",
        title: "Setup data pipeline Clickhouse",
        description: "Konfigurasi Clickhouse sebagai OLAP database dan buat schema untuk event tracking.",
        status: "in-progress",
        priority: "urgent",
        assigneeId: "u2",
        dueDate: "2026-03-10T00:00:00Z",
        startDate: "2026-02-25T00:00:00Z",
        tags: ["database", "analytics"],
        createdAt: "2026-02-20T08:00:00Z",
        updatedAt: "2026-03-04T11:00:00Z",
    },
    {
        id: "t13",
        projectId: "p4",
        title: "Chart library evaluation dan setup (Recharts/Victory)",
        description: "Evaluasi library chart yang paling sesuai: performa, bundle size, dan kemudahan kustomisasi.",
        status: "done",
        priority: "medium",
        assigneeId: "u3",
        dueDate: "2026-03-01T00:00:00Z",
        startDate: "2026-02-22T00:00:00Z",
        tags: ["research", "frontend"],
        createdAt: "2026-02-20T08:00:00Z",
        updatedAt: "2026-03-01T10:00:00Z",
    },
    {
        id: "t14",
        projectId: "p4",
        title: "Buat komponen KPI card dengan trend indicator",
        description: "Komponen reusable yang menampilkan nilai KPI, persentase perubahan, dan mini sparkline chart.",
        status: "todo",
        priority: "high",
        assigneeId: "u4",
        dueDate: "2026-03-15T00:00:00Z",
        startDate: "2026-03-08T00:00:00Z",
        tags: ["frontend", "component"],
        createdAt: "2026-02-20T08:00:00Z",
        updatedAt: "2026-02-20T08:00:00Z",
    },
    {
        id: "t15",
        projectId: "p4",
        title: "Real-time WebSocket untuk live metrics",
        description: "Implementasi WebSocket connection untuk update data tanpa perlu refresh halaman.",
        status: "todo",
        priority: "high",
        assigneeId: "u2",
        dueDate: "2026-03-20T00:00:00Z",
        startDate: "2026-03-12T00:00:00Z",
        tags: ["backend", "websocket"],
        createdAt: "2026-02-20T08:00:00Z",
        updatedAt: "2026-02-20T08:00:00Z",
    },
];

// Helper to get tasks for a specific project
export function getProjectTasks(projectId: string): Task[] {
    return mockTasks.filter((t) => t.projectId === projectId);
}

// Helper to get user by id
export function getUserById(userId: string): User | undefined {
    return mockUsers.find((u) => u.id === userId);
}

// Get tasks assigned to current user
export function getMyTasks(): Task[] {
    return mockTasks.filter((t) => t.assigneeId === currentUser.id);
}

// Get overdue tasks
export function getOverdueTasks(): Task[] {
    const now = new Date();
    return mockTasks.filter(
        (t) => t.dueDate && new Date(t.dueDate) < now && t.status !== "done"
    );
}
